BASICS:
  train_dir:   ./data/BASICS/ 
  test_dir:    ./data/BASICS/  
  valid_dir:   ./data/BASICS/

PointXR:
  train_dir:   ./data/PointXR/ 
  test_dir:    ./data/PointXR/  
  valid_dir:   ./data/PointXR/

ICIP20:
  train_dir:   ./data/ICIP20/ 
  test_dir:    ./data/ICIP20/  
  valid_dir:   ./data/ICIP20/

point_size: 1024
patch_size: 100

input_channel: 9
input_size: 32
